{
 "title": "Jitsi",
 "time": { "from": "2020-03-12T23:33:54.710Z", "to": "2020-03-12T23:57:13.959Z" },
 "panels": [
  {
   "title": "participants",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jitsi_participants", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "cpu usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jitsi_cpu_usage", "legendFormat": "cpu usage" }
   ]
  },
  {
   "title": "conferences",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jitsi_conferences", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jitsi_total_memory", "legendFormat": "total {{instance}}" },
    { "expr": "jitsi_used_memory", "legendFormat": "used {{instance}}" }
   ]
  }
 ]
}